# Define object location as [x, y, theta]
location1: [2.0, 0.0, 0]
location2: [2.0,-2.0, 90]
location3: [0.0, -2.0, 180]
location4: [0.0, 0.0, -90]
# location1: [0.5, -0.5, -90]
# location2: [3.5,-0.75, -90]
# location3: [1.8, -3.2, -90]
# location4: [-1.5, -3, -90]
# location5: [0,-5.6, -90]
# location6: [3.2, -5.8, -90]
# location7: [-1.7,-8.3, -90]